kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-ssd
  resources:
    requests:
      storage: 40Gi
