apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: ci
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
         claimName: mysql-ci
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - name: tcp
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: J7nn83cm02431234
        - name: MYSQL_DATABASE
          value: jira
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql

