kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab
  namespace: ci
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: alicloud-disk-ssd
  resources:
    requests:
      storage: 20Gi
