kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      whatfor: "airflow-dags"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-logs
  labels:
    app: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      whatfor: "airflow-logs"

